### ISSUE TITLE
More verbose errors? - Troubleshooting "No such file or directory"

### ISSUE THREAD

**Issue by seanmcardwell** [Kaiede/Bedrockifier#34]
Is there any way to enable a more verbose error? I'm getting the error `The operation could not be completed. No such file or directory` I've double checked all my paths and tried from scratch again, and it's complaining no such file or directory. But I don't know which file or directory it's failing at.

Any suggestions? Docker Compose and config files attached. I've got a directory variable set in my .env. Though I've tried with an absolute path with no luck as well. 

[dc-minecraft.yml.txt](https://github.com/Kaiede/Bedrockifier/files/8137223/dc-minecraft.yml.txt)
[config.yml.txt](https://github.com/Kaiede/Bedrockifier/files/8137234/config.yml.txt)

**Comment by Kaiede** [comment]
The config.yml will let you set the logging level, and is documented in the wiki: https://github.com/Kaiede/Bedrockifier/wiki/Configuration-File#logging-level

The trace level logs in particular can be very noisy as nearly every little thing will get logged, and I have had feedback that errors can be hard to see in those logs. 

In terms of the config file I do see this:

```
containers:
  minecraft:
    - name: "Council of Nerds"
      worlds:
        - "/server/worlds/CouncilofNerds"
```

This should be:

```
containers:
  bedrock: # type of container
    - name: minecraft # container name
      worlds:
        - "/server/worlds/CouncilofNerds" # path to world
```
Containers is split into bedrock/java since the service supports backing up both types of servers, but needs to know which type it is. 

As an aside, this also jumped out, but in a good way:
```
- /var/run/docker.sock:/var/run/docker.sock:ro
```
After reading up on this, it seems like it should work and provides some useful security. I should probably test it myself and add it to the Wiki instructions. Today I learned something new.

**Comment by Kaiede** [comment]
I will also note that your schedule pretty much means that only the 12h interval timer will fire (per the documentation at https://github.com/Kaiede/Bedrockifier/wiki/Configuration-File#schedule): 

```
schedule:
  onLastLogout: true
  interval: 12h
  minInterval: 12h
```

minInterval needs to be less than interval so that 'onLastLogout' will actually perform backups.

That said, I'm curious what you wanted this to do. I could always add a small feature to make it possible to configure it the way you were trying to.

**Comment by seanmcardwell** [comment]
Thanks for the quick response!

To be honest I was setting this up in the background on my lunch so I might have just misread on the intervals. I wanted it to Save either every 12 hours, or when the last player logs out. So i can probably just adjust the minInterval down so that'll happen. 

And ahh makes sense on the config file. I did not compute the "type of container" to be bedrock vs java. That's probably my actual issue. I'll try that in a bit

And hah glad the read-only docker.sock popped out so my issue wasn't a totally useless user-error. I learned that recently it was safer to do that too. So I was planning on trying it first and seeing if it worked. I assumed it only needed read only access based off what I assumed the container was doing.

**Comment by Kaiede** [comment]
> To be honest I was setting this up in the background on my lunch so I might have just misread on the intervals. I wanted it to Save either every 12 hours, or when the last player logs out. So i can probably just adjust the minInterval down so that'll happen.

For something like this it really depends on how many backups per day you are willing to accept before trimming can cut it down to the single daily. 

For example, if I wanted to limit things to a max of 8 backups a day, but guarantee 2 a day minimum, then something like this would make sense:

```
schedule:
  onLastLogout: true
  interval: 12h
  minInterval: 3h
```

The net effect is that when logouts happen near the 12h interval, those get "coalesced" into a single backup near the 12h interval. 

> And hah glad the read-only docker.sock popped out so my issue wasn't a totally useless user-error. I learned that recently it was safer to do that too. So I was planning on trying it first and seeing if it worked. I assumed it only needed read only access based off what I assumed the container was doing.

The service does need to write _to_ the socket file, but apparently "ro" still allows that in this case. But seeing that it should block the file from being deleted by the container on accident, I like it being there.

**Comment by Kaiede** [comment]
This issue has been idle for a few days. I just wanted to ping to see if this has helped you or not?

**Comment by seanmcardwell** [comment]
I did make the config changes you mentioned to my config.yml file with no luck. I was still experiencing the same issues where the container would just constantly restart, and was complaining about the path not existing. 

I was trying to figure out how to exec into the container and poke around to see what it's seeing, but since it's dying to fast I hadn't been successful. I'm relatively new to debugging docker containers in that way. 

I also did try with a fresh Minecraft container and backup container in a different directory to see if there was any issues related to my symlinks, and also had no luck. 

So I've left this alone for a bit and was going to come back to it. If you have any ideas I'm all ears, but I'll also let you know if I figure anything else out as well.

**Comment by Kaiede** [comment]
If you have the verbose logs, I'd probably have to see what's in them to have any further ideas. Sometimes just seeing the context around an error is important to know where in the code the error is happening.

**Comment by Kaiede** [comment]
Unfortunately, this is approaching a couple weeks without any new updates, and I am unable to do anything further without more information to work with. So for now, I'm closing this as inactive.

But please, if you are able to look at this again and can provide verbose log snippets, feel free to reopen with those additional details.
