### ISSUE TITLE
WSL docker sock mount failed

### ISSUE THREAD

**Issue by weihao** [Kaiede/Bedrockifier#47]
```
time="2022-03-15T13:00:32-04:00" level=debug msg="Using /backups to match uid and gid"
time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved UID=1000 from match path"
time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved GID=1000 from match path"
time="2022-03-15T13:00:32-04:00" level=debug msg="stdin is detached, so forwarding is disabled"
[13:00:32.753][info    ] Initializing Bedrockifier Daemon
[13:00:32.758][info    ] Loading Configuration From: /backups/config.yml
[13:00:32.763][info    ] Configuration Loaded, Entering Event Loop...
[13:00:32.778][info    ] Host PTY Handle Opened: /dev/pts/0 (3)
[13:00:32.778][info    ] Child PTY Handle Opened: /dev/pts/0 (4)
[13:00:32.779][info    ] Backup Interval: 10800.0 seconds
[13:00:32.780][info    ] Starting Full Backup
[13:00:32.805][error   ] Docker was blocked from accessing docker.sock, make sure UID/GID are set correctly
[13:00:32.805][error   ] Container survival failed to backup properly
[13:00:32.805][info    ] Performing Trim Jobs
[13:00:32.813][info    ] Full Backup Completed
```

```
  backup:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    depends_on:
      - "survival"
    environment:
      BACKUP_INTERVAL: "12h"
      TZ: "America/New_York"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/backups
      - ./survival:/survival
```

**Comment by Kaiede** [comment]
As the error says, docker was blocked due to permissions.

[Per the wiki](https://github.com/Kaiede/Bedrockifier/wiki/Permissions):

> By default it will automatically demote the service to the user and group that owns your backups directory. In many cases you can use a regular user that has been added to the docker group (ex. `me:docker`).

In the log you can see the UID/GID that the service used:

> time="2022-03-15T13:00:32-04:00" level=debug msg="Using /backups to match uid and gid"
time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved UID=1000 from match path"
time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved GID=1000 from match path"

GID 1000 isn't the `docker` group on most Linux installs.

So you have two options: 

1) chown the backups folder to `<youruser>:docker` and restart the service.
2) Set the `GID` variable in your `docker-compose.yml` to be the ID of the docker group on your system.

**Comment by weihao** [comment]
> As the error says, docker was blocked due to permissions.
> 
> [Per the wiki](https://github.com/Kaiede/Bedrockifier/wiki/Permissions):
> 
> > By default it will automatically demote the service to the user and group that owns your backups directory. In many cases you can use a regular user that has been added to the docker group (ex. `me:docker`).
> 
> In the log you can see the UID/GID that the service used:
> 
> > time="2022-03-15T13:00:32-04:00" level=debug msg="Using /backups to match uid and gid"
> > time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved UID=1000 from match path"
> > time="2022-03-15T13:00:32-04:00" level=debug msg="Resolved GID=1000 from match path"
> 
> GID 1000 isn't the `docker` group on most Linux installs.
> 
> So you have two options:
> 
> 1. chown the backups folder to `<youruser>:docker` and restart the service.
> 2. Set the `GID` variable in your `docker-compose.yml` to be the ID of the docker group on your system.

I tried both options and it still gave me the same error. We need more info in the log to debug

**Comment by Kaiede** [comment]
> I tried both options and it still gave me the same error. We need more info in the log to debug

The new issue templates include details on how to do this. Specifically for the Error Report template, it does ask folks to turn on verbose logging and describes how to do so. The details are also in the wiki: https://github.com/Kaiede/Bedrockifier/wiki/Configuration-File#logging-level

That said, what is the GID being reported now? Is it still 1000?

This error though is very specific, and is related to ownership/permissions to the docker.sock file. It only shows up when docker returns "Got permission denied while trying to connect to the Docker daemon" when attempting to run `docker attach`.

**Comment by weihao** [comment]
GID is still 1000.

Docker attach just hangs, do i need to open tty and make it interactive?

**Comment by Kaiede** [comment]
> GID is still 1000.

That’s odd. Did you create a docker group when setting it up? You might need to manually set the GID variable to the docker group’s ID.

> Docker attach just hangs, do i need to open tty and make it interactive?

There was a fix late December to no longer require tty on the server containers. But `stdin_open: true` is still required on the server contains, otherwise no commands can flow to the server, which are required to avoid corruption of the backups..

**Comment by weihao** [comment]
`stdin_open: true` did not work. docker attach still hangs.

I have created the docker group.

**Comment by weihao** [comment]
setting GID with a newly created docker group id as an environment variable worked.

thanks!
