### ISSUE TITLE
[Suggestion] Post backup commands

### ISSUE THREAD

**Issue by DanTheMan827** [Kaiede/Bedrockifier#50]
Being able to specify post-backup commands could be useful for users running in certain environments, these commands would run after Bedrockifier has finished doing everything with the file.

It may be something like a special chown/chmod, or perhaps even completely situation specific things like padding the `.mcworld` file to a minimum of 1GB so that Crashplan will upload the file at full speed by not doing block-level de-duplication.

It could also let users do something like trigger an rsync to a remote share on a backup server.

For specifying the path to the backup file, you could do something like the find command does for exec, and replace `{}` with the properly quoted path.

**Comment by Kaiede** [comment]
I like the idea, At the very least it makes similar requests of post-processing more sustainable and common tricks can be added to the wiki. 

Dependencies would need to be managed in some way, like in the rsync example, to ensure the tools expected are available from within the container, but so long as it is available via apt in Ubuntu, it should be pretty straight-forward.

**Comment by DanTheMan827** [comment]
For dependencies, you could have a Docker variable containing a list of packages to install, or perhaps a directory people can drop packages into that dpkg installs

it does go against the idea of modifying the Docker after install, but I’ve seen other containers do it this way

**Comment by Bob0t** [comment]
Hey, I'm pretty sure you can handle it with an event into another container, like mc-webhook does ? :)

**Comment by Kaiede** [comment]
> Hey, I'm pretty sure you can handle it with an event into another container, like mc-webhook does ? :)

Good catch here. Bringing that functionality within the container does pose some risk. It would be a lot easier to build a simple monitor script inside another container. So it might be better if the effort I spent was on creating a small demo container + documentation on how to do something like that. Maybe use the NAS file ownership feature as the template.

And today I learned that mc-webhook even works against the backup container out of the box. Neat. Now I want to play with that.

**Comment by Kaiede** [comment]
And just as a side note, I am not trying to ignore the open issues, but I have been working long hours the last couple months, so I haven't had as much time to devote to this project as I'd like.

**Comment by Kaiede** [comment]
After thinking on this, I don’t think we will ever want to run this much stuff in the container. There’s just too much variability in what people will want, and it creates security concerns. Especially with things like docker-compose, it’s easy to chain a few simple containers to build pretty much anything you want. The suggestion for now is to use `mc-webhook` for this sort of thing. It supports both triggering MQTT and HTTP endpoints, and works by tailing the logs from the backup service. 

However, I do want to provide some sort of built-in callback system for events that can be used with a microservice (e.g. in python) that can then do whatever you want. This would be part of a monitoring API that the service would expose that I am tracking with #93.
