### ISSUE TITLE
Error with compose file on wiki

### ISSUE THREAD

**Issue by chelming** [Kaiede/Bedrockifier#57]
The [compose example on the wiki](https://github.com/Kaiede/Bedrockifier/wiki#configure-docker-compose-file) has `name` where it should instead be [container_name](https://docs.docker.com/compose/compose-file/#container_name).

```
$ docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.backup: 'name'
```

```
$ docker-compose -v
docker-compose version 1.25.0, build unknown
```

**Comment by Kaiede** [comment]
I’ve updated the wiki and double checked the examples under Docker/examples. Thanks for the report.
