### ISSUE TITLE
[Synology Docker] Docker was blocked from accessing docker.sock, make sure UID/GID are set correctl

### ISSUE THREAD

**Issue by Railsimulatornet** [Kaiede/Bedrockifier#65]
Good evening, I've been trying for half the day to get the backup to work, unfortunately without success.

I don't know what to do and I hope you can help here:

![grafik](https://user-images.githubusercontent.com/29884757/222223749-2a63070a-2b48-4234-982c-d57403b24453.png)

![grafik](https://user-images.githubusercontent.com/29884757/222223825-3ac76998-552d-4fe7-88ab-782a45f8867f.png)
![grafik](https://user-images.githubusercontent.com/29884757/222223892-9081b2b3-458a-41e0-8dbc-467c055aae23.png)
![grafik](https://user-images.githubusercontent.com/29884757/222223926-49107f69-d162-4d3b-9222-100a412ad331.png)

**Comment by Kaiede** [comment]
For the container to work, it needs access to the docker.sock file that the _docker instance on the Synology is using_. /docker/docker.sock isn't usually it, but instead it would normally live at /var/run/docker.sock (it does on my Synology NAS). 

The UID/GID also need to be set such that it runs with permissions to read/write to that file. So with the Synology running docker as root, you will need to run the container as root too. UID/GID aren't set in the YML, but rather set as environment variables for the docker container (my backup tool relies on the same mechanisms that itzg uses for the Minecraft server to set the user/group of the running server).

**Comment by Railsimulatornet** [comment]
Many thanks.

![grafik](https://user-images.githubusercontent.com/29884757/222349497-794b8afc-784d-476f-a2d2-d236c6852ac3.png)


It works now.
