### ISSUE TITLE
support sending backups off the host

### ISSUE THREAD

**Issue by bsdlp** [Kaiede/Bedrockifier#66]
**Is your feature request related to a problem? Please describe.**
I would love to be able to store my backups off of the server that is hosting my minecraft server

**Describe the solution you'd like**
Bedrockifier would create the snapshots as usual and optionally can run a user configured command to ship snapshots to another location, like via ssh to another server or s3.

**Describe alternatives you've considered**
since bedrockifier is running in docker, one option is to write snapshots to a docker volume then have a trigger that ships those snapshots off. However, there is not a great way to notify when snapshots are written.

**Additional context**

**Comment by Kaiede** [comment]
This is something that I’d consider to be outside the scope of the project. However, I would be open to changes to make it easier to integrate with other tools if there’s something specific you are attempting to do.

For my own off-site backups, I use a duplicati instance to push the snapshots folder to B2 storage once a day after the nightlies have run:
https://hub.docker.com/r/linuxserver/duplicati

**Comment by bsdlp** [comment]
ah yeah that's what i landed on as well - slightly worried about the very small chance that bedrockifier is writing while the offsite push is happening but i dont think it's a big deal since the sync will fix it all
